kind: pipeline
name: default
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://3.0.177.36:8081
    username: admin_name
    password: admin_password
-   pom: pom.xml
+   group_id: com.mindtree 
+   artifact_id: BasicApp
+   version: SNAPSHOT-0.0.1
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
+   force_upload: true      
