kind: pipeline
name: default
steps:
- name: build_war
  image: maven:alpine
  commands:
  - mvn --batch-mode clean install
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token 
- name: deploy_war 
  image: maven
  settings:
    url:
      from_secret: ARTIFACTORY_URL
    username:
      from_secret: ARTIFACTORY_USER
    password:
      from_secret: ARTIFACTORY_PASSWORD
    repo_key:
      from_secret: REPOSITORY_KEY
  commands:
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD
