kind: pipeline
name: default
pipeline:
  artifactory:
    image: plugins/drone-artifactory
    url: http://54.169.222.113:8081/artifactory/Hello/
    username: admin
    password: password
    pom: pom.xml
    repo_key: Hello
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
    force_upload: true
