kind: pipeline
name: default
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://3.0.177.36:8081
    username: admin_name
    password: admin_password
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
