kind: pipeline
name: default
steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn clean install
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://arti.company.com
    username: admin_name
    password: password_password
    files:
      - target/*.war
    
