kind: pipeline
name: default
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://54.169.222.113:8081/artifactory/webapp/#/artifacts/browse/tree/General/Hello
    username: admin_name
    password: admin_password
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
      
