kind: pipeline
name: default
steps:
- name: build_war
  image: maven:alpine
  commands:
  - mvn --batch-mode clean install
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token 
- name: deploy_war 
  image: athieriot/drone-artifactory
  settings:
    url: http://jfrog.com/
    username: admin
    password: password
    pom: pom.xml
    repo_key: Hello
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war

