kind: pipeline
name: default
steps:
- name: build_war
  image: maven:alpine
  commands:
  - mvn --batch-mode clean install
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: deploy_war 
  image: jmccann/drone-artifactory
  settings:
    url: http://54.169.222.113:8081
    username: admin
    password:
      from_secret: artifactory_password
    pom: pom.xml
    repo_key:
      from_secret: repository_key
    files:
      - target/*.war
      
