pipeline:
  deploy_war:
    image: athieriot/drone-artifactory:latest
    url: http://54.169.222.113:8081/artifactory/Hello/
    username: admin
    password: password
    pom: pom.xml
    repo_key: Hello
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
    when:
      branch: master
