kind: pipeline
name: default
pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://arti.company.com
    username: admin
    password: password
    pom: pom.xml
    files:
      - target/*.war
