kind: pipeline
name: default
pipeline:
  artifactory:
    image: emeraldsquad/artifactory-resource
    url: 54.169.222.113:8081
    username: admin
    password: password
    pom: pom.xml
    files:
      - target/BasicApp-0.0.1-SNAPSHOT.war
      



  
    
    
      
